name: Release

on:
  release:
    types: [published]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    runs-on: ubuntu-latest
    needs: [build-javascript, build-rust, build-python]
    if: github.event_name == 'release'

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            api.github.com:443
            crates.io:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            static.crates.io:443
            static.rust-lang.org:443

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{ github.head_ref }}

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable

      - name: Install wasm-pack # need a build from master for https://github.com/rustwasm/wasm-pack/pull/839
        run: cargo install --git https://github.com/rustwasm/wasm-pack --rev d46d1c6

      - name: Set up Python 3.8
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: 3.8

      - run: |
          pip install twine==3.2

      - uses: actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869 # v2.1.0
        with:
          name: python-wheel
          path: python-wheel

      - name: Update version
        run: |
          bash update_version.sh ${{ github.event.release.tag_name }}

      - name: Run release script
        run: |
          bash release.sh
        env:
          CARGO_KEY: ${{ secrets.CARGO_KEY }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          WHEEL_DIR: python-wheel

      - run: |
          rm -r python-wheel

      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        with:
          commit_message: v${{ github.event.release.tag_name }}
          branch: main
